# Generated by Django 3.1 on 2020-09-06 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200905_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_posts', to='api.tag'),
        ),
    ]
